# **Group-5 Machine Learning Programming (PROG8245)**
# **Final Project Model Development**

### **Import the Required Packages**

In [3]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

import pandas as pd

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dwara\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dwara\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dwara\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

### **Importing the Data**

In [10]:
# Importing the tweets dataset

df = pd.read_csv(r"C:\Users\dwara\OneDrive\Desktop\ML_Programming\Labs\MLP_Project\MLP_Assignment_1\data\hugginoutput.csv")
df.columns = ['tweets', 'sentiment']
df

tweets sentiment
0    Ngoc Pham, a 83 yr old Vietnamese man, was one...  negative
1    I’m making the following announcement and form...  positive
2    “The most aggressive field operation in Califo...  positive
3    Thank you Supervisor @AaronPeskin for endorsin...  positive
4    #tbt sharing a meal w/my friend @narendramodi ...  positive
..                                                 ...       ...
444  Hey @united, I’m about to board one of your fl...   neutral
445  OFFICIAL WELCOME: @MikePenceVP let me be the f...  positive
446  BREAKING: A Republican Member of the Pennsylva...  negative
447  Today, I'm joined by 8 of my colleagues in int...  negative
448  I'm introducing legislation to ban the use of ...  negative

[449 rows x 2 columns]

### **Basic Preprocessing of Tweets**

In [11]:
# Initialize NLP Preprocessing functions

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

# Preprocess the "tweets" column in place

for index, row in df.iterrows():
    sentence = row['tweets']
    
    # Tokenize the sentence
    tokens = word_tokenize(sentence)
    
    # Remove punctuation and convert to lowercase
    tokens = [token.lower() for token in tokens if token.isalnum()]
    
    # Remove stopwords
    tokens = [token for token in tokens if token not in stop_words]
    
    # Lemmatize tokens
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    # Join tokens back into a preprocessed sentence
    preprocessed_sentence = ' '.join(lemmatized_tokens)
    
    # Update the "tweets" column with preprocessed sentence
    df.at[index, 'tweets'] = preprocessed_sentence

# Display the DataFrame
df

tweets sentiment
0    ngoc pham 83 yr old vietnamese man one 2 asian...  negative
1    making following announcement formal apology t...  positive
2    aggressive field operation california sander a...  positive
3    thank supervisor aaronpeskin endorsing senator...  positive
4    tbt sharing meal friend narendramodi wishing l...  positive
..                                                 ...       ...
444  hey united board one flight sure hope given fl...   neutral
445  official welcome mikepencevp let first officia...  positive
446  breaking republican member pennsylvania house ...  negative
447  today joined 8 colleague introducing walk with...  negative
448  introducing legislation ban use tear gas distr...  negative

[449 rows x 2 columns]

### **Word Embeddings Creation using tfidf vectors**

In [106]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF vectorizer

tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the preprocessed tweets

tfidf_matrix = tfidf_vectorizer.fit_transform(df['tweets'])

# Convert the TF-IDF matrix to a DataFrame

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# Concatenate the original DataFrame with the TF-IDF DataFrame

tfidf_df = pd.concat([df, tfidf_df], axis=1)

# Remove the sentence_embeddings column

tfidf_df = tfidf_df.drop(columns=['sentence_embeddings'])

# Display the final output dataframe with embeddings

tfidf_df


tweets sentiment   10  100k   
0    ngoc pham 83 yr old vietnamese man one 2 asian...  negative  0.0   0.0  \
1    making following announcement formal apology t...  positive  0.0   0.0   
2    aggressive field operation california sander a...  positive  0.0   0.0   
3    thank supervisor aaronpeskin endorsing senator...  positive  0.0   0.0   
4    tbt sharing meal friend narendramodi wishing l...  positive  0.0   0.0   
..                                                 ...       ...  ...   ...   
444  hey united board one flight sure hope given fl...   neutral  0.0   0.0   
445  official welcome mikepencevp let first officia...  positive  0.0   0.0   
446  breaking republican member pennsylvania house ...  negative  0.0   0.0   
447  today joined 8 colleague introducing walk with...  negative  0.0   0.0   
448  introducing legislation ban use tear gas distr...  negative  0.0   0.0   

     10am   11   13   14  15th   16  ...      year  yes  yesterday  yet  york   
0     0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.186308  0.0   0.0  \
1     0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   
2     0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   
3     0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   
4     0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   
..    ...  ...  ...  ...   ...  ...  ...       ...  ...        ...  ...   ...   
444   0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   
445   0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   
446   0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   
447   0.0  0.0  0.0  0.0   0.0  0.0  ...  0.137571  0.0   0.000000  0.0   0.0   
448   0.0  0.0  0.0  0.0   0.0  0.0  ...  0.000000  0.0   0.000000  0.0   0.0   

     young  youngest        yr  zelenskyy     zero  
0      0.0       0.0  0.340949        0.0  0.00000  
1      0.0       0.0  0.000000        0.0  0.00000  
2      0.0       0.0  0.000000        0.0  0.00000  
3      0.0       0.0  0.000000        0.0  0.00000  
4      0.0       0.0  0.000000        0.0  0.00000  
..     ...       ...       ...        ...      ...  
444    0.0       0.0  0.000000        0.0  0.00000  
445    0.0       0.0  0.000000        0.0  0.00000  
446    0.0       0.0  0.000000        0.0  0.00000  
447    0.0       0.0  0.000000        0.0  0.20922  
448    0.0       0.0  0.000000        0.0  0.00000  

[449 rows x 2245 columns]

### **Word Embeddings creation using Word2Vec Skipgram Model**

In [107]:
from gensim.models import Word2Vec

# Train the Word2Vec model

model = Word2Vec(sentences=df['tweets'], vector_size=500, window=5, sg=1, min_count=1)

# Create a list to store tweet embeddings

tweet_embeddings = []

# Calculate the average embedding for each token in each tweet

for tokens in df['tweets']:
    embeddings = [model.wv[token] for token in tokens if token in model.wv]
    if embeddings:
        tweet_embedding = sum(embeddings) / len(embeddings)
    else:
        tweet_embedding = [0] * model.vector_size  # Assigning zero vector for out-of-vocabulary words
        
    tweet_embeddings.append(tweet_embedding)

# Convert the list of embeddings to a DataFrame
tweet_embeddings_df = pd.DataFrame(tweet_embeddings, columns=[f'feature_{i}' for i in range(model.vector_size)])

# Concatenate the original DataFrame with the tweet embeddings DataFrame
word2vec_df = pd.concat([df, tweet_embeddings_df], axis=1)

# Remove the sentence_embeddings column
word2vec_df = word2vec_df.drop(columns=['sentence_embeddings'])

# Display the modified DataFrame
word2vec_df

tweets sentiment  feature_0   
0    ngoc pham 83 yr old vietnamese man one 2 asian...  negative   0.076744  \
1    making following announcement formal apology t...  positive   0.076372   
2    aggressive field operation california sander a...  positive   0.076763   
3    thank supervisor aaronpeskin endorsing senator...  positive   0.075840   
4    tbt sharing meal friend narendramodi wishing l...  positive   0.076430   
..                                                 ...       ...        ...   
444  hey united board one flight sure hope given fl...   neutral   0.077678   
445  official welcome mikepencevp let first officia...  positive   0.075786   
446  breaking republican member pennsylvania house ...  negative   0.075425   
447  today joined 8 colleague introducing walk with...  negative   0.076657   
448  introducing legislation ban use tear gas distr...  negative   0.076289   

     feature_1  feature_2  feature_3  feature_4  feature_5  feature_6   
0     0.030947   0.046186   0.010292  -0.081016  -0.083532  -0.008621  \
1     0.030456   0.045402   0.010186  -0.080341  -0.082916  -0.008668   
2     0.030808   0.045769   0.009861  -0.080629  -0.082838  -0.008533   
3     0.030218   0.045851   0.009287  -0.080463  -0.081054  -0.007640   
4     0.030484   0.045450   0.010247  -0.080818  -0.082362  -0.008108   
..         ...        ...        ...        ...        ...        ...   
444   0.031790   0.046427   0.010435  -0.081350  -0.083798  -0.008335   
445   0.030676   0.045305   0.009415  -0.080681  -0.082691  -0.008398   
446   0.030888   0.045796   0.009012  -0.080354  -0.082336  -0.008419   
447   0.030596   0.045268   0.010127  -0.080485  -0.082908  -0.008490   
448   0.030963   0.045718   0.009371  -0.080902  -0.083031  -0.008512   

     feature_7  ...  feature_490  feature_491  feature_492  feature_493   
0     0.120812  ...     0.043578    -0.012962     0.054955     0.058670  \
1     0.119791  ...     0.043976    -0.013322     0.054382     0.058117   
2     0.120222  ...     0.044042    -0.012846     0.055301     0.058937   
3     0.117877  ...     0.046128    -0.014048     0.057207     0.060641   
4     0.119774  ...     0.043510    -0.013013     0.054999     0.058280   
..         ...  ...          ...          ...          ...          ...   
444   0.122458  ...     0.043204    -0.012310     0.055704     0.058883   
445   0.119785  ...     0.043199    -0.012608     0.054249     0.057894   
446   0.119384  ...     0.043581    -0.012802     0.054780     0.058419   
447   0.120148  ...     0.044267    -0.013269     0.055046     0.058660   
448   0.120549  ...     0.044090    -0.012860     0.055055     0.058658   

     feature_494  feature_495  feature_496  feature_497  feature_498   
0       0.016228     0.008017    -0.011431     0.026834    -0.042793  \
1       0.016160     0.008301    -0.011921     0.026654    -0.042991   
2       0.016421     0.008672    -0.011221     0.026781    -0.043898   
3       0.015682     0.010607    -0.013825     0.027092    -0.045812   
4       0.015952     0.008525    -0.011212     0.026109    -0.043871   
..           ...          ...          ...          ...          ...   
444     0.016722     0.007232    -0.010740     0.026866    -0.042810   
445     0.015946     0.008372    -0.011760     0.026246    -0.042728   
446     0.016179     0.008328    -0.012356     0.026490    -0.042990   
447     0.016116     0.008503    -0.012054     0.026910    -0.043462   
448     0.016414     0.008125    -0.011971     0.026665    -0.043584   

     feature_499  
0       0.018279  
1       0.017968  
2       0.018478  
3       0.019946  
4       0.018485  
..           ...  
444     0.018456  
445     0.018454  
446     0.018683  
447     0.018230  
448     0.018848  

[449 rows x 502 columns]

### **Word Embeddings Creation using BERT**

In [108]:
from transformers import BertTokenizer, BertModel
import torch
import pandas as pd

# Load the BERT model and tokenizer
model_name = 'bert-base-uncased'
model = BertModel.from_pretrained(model_name)
tokenizer = BertTokenizer.from_pretrained(model_name)


# Initialize lists to store sentence embeddings
sentence_embeddings_list = []

# Loop through each row in the DataFrame
for index, row in df.iterrows():
    sentence = row['tweets']
    
    # Tokenize the sentence and convert to token IDs
    tokens = tokenizer.encode(sentence, add_special_tokens=True)
    token_ids = torch.tensor(tokens).unsqueeze(0)
    
    # Create attention mask
    attention_mask = token_ids != 0
    
    # Run a forward pass through BERT
    with torch.no_grad():
        outputs = model(token_ids, attention_mask)
    encoded_layer = outputs.last_hidden_state
    
    # Calculate sentence embedding (mean of all word embeddings)
    sentence_embedding = encoded_layer.mean(dim=1)
    sentence_embeddings_list.append(sentence_embedding[0].tolist())

# Convert sentence embeddings to a NumPy array
sentence_embeddings_array = torch.tensor(sentence_embeddings_list).numpy()

# Create a new DataFrame with original tweets, sentiment, and sentence embedding features
embedding_df = pd.concat([
    df[['tweets', 'sentiment']],
    pd.DataFrame(sentence_embeddings_array, columns=[f"feature_{i}" for i in range(sentence_embeddings_array.shape[1])])
], axis=1)

# Display the embedding DataFrame
embedding_df

tweets sentiment  feature_0   
0    ngoc pham 83 yr old vietnamese man one 2 asian...  negative   0.151141  \
1    making following announcement formal apology t...  positive   0.019772   
2    aggressive field operation california sander a...  positive   0.131454   
3    thank supervisor aaronpeskin endorsing senator...  positive  -0.179532   
4    tbt sharing meal friend narendramodi wishing l...  positive  -0.295412   
..                                                 ...       ...        ...   
444  hey united board one flight sure hope given fl...   neutral   0.160700   
445  official welcome mikepencevp let first officia...  positive   0.375342   
446  breaking republican member pennsylvania house ...  negative   0.049125   
447  today joined 8 colleague introducing walk with...  negative   0.151372   
448  introducing legislation ban use tear gas distr...  negative   0.309776   

     feature_1  feature_2  feature_3  feature_4  feature_5  feature_6   
0     0.182959   0.402899  -0.305875   0.315593   0.111646   0.240216  \
1    -0.119633   0.667289  -0.449308   0.104519  -0.161934   0.494147   
2    -0.080869   0.196176  -0.031682   0.272633  -0.090877  -0.003943   
3    -0.021509   0.155459   0.038721   0.035100  -0.155799  -0.217436   
4    -0.332681   0.301100  -0.227789   0.419574  -0.102872   0.474347   
..         ...        ...        ...        ...        ...        ...   
444  -0.260867   0.497267  -0.093050   0.434605  -0.042255   0.389752   
445   0.046244   0.656258  -0.028738   0.071722  -0.131102   0.444305   
446  -0.283249  -0.012151   0.157952   0.084787  -0.151598   0.047349   
447  -0.096814   0.387434  -0.147987   0.238097  -0.200005   0.261640   
448  -0.021357  -0.123608  -0.259325  -0.038622  -0.198144   0.340735   

     feature_7  ...  feature_758  feature_759  feature_760  feature_761   
0     0.425379  ...    -0.032087    -0.201522     0.287459    -0.229566  \
1     0.455437  ...     0.321194    -0.011513     0.353712    -0.126999   
2     0.249903  ...    -0.086666    -0.123839    -0.198244    -0.371338   
3    -0.008971  ...    -0.092380    -0.059386     0.015992     0.098745   
4     0.239754  ...    -0.031311     0.160330     0.354961    -0.036209   
..         ...  ...          ...          ...          ...          ...   
444   0.375278  ...    -0.004017    -0.408482     0.171101    -0.064507   
445   0.248182  ...     0.204532    -0.196501     0.063307    -0.169355   
446  -0.334749  ...     0.086166     0.273918    -0.085442     0.097800   
447   0.234046  ...     0.222576     0.150740     0.143877    -0.265047   
448  -0.006078  ...     0.168060     0.057625     0.129071    -0.086706   

     feature_762  feature_763  feature_764  feature_765  feature_766   
0       0.076743     0.075291    -0.147191    -0.154748    -0.033774  \
1       0.142262    -0.122046    -0.075087    -0.075467     0.016284   
2       0.314498     0.145142    -0.303607    -0.183542    -0.109382   
3       0.338740     0.007371    -0.223407     0.085241    -0.032808   
4      -0.098433     0.072526     0.065840    -0.350750     0.079152   
..           ...          ...          ...          ...          ...   
444    -0.007335     0.129339    -0.141256    -0.311000    -0.030480   
445     0.228348     0.204946    -0.358443    -0.099012    -0.088422   
446     0.475979    -0.040850    -0.036262    -0.077140    -0.142727   
447     0.493757    -0.082712    -0.207422    -0.457475    -0.221328   
448     0.475074    -0.186304    -0.009041    -0.338859    -0.281377   

     feature_767  
0       0.058169  
1       0.045438  
2      -0.375275  
3       0.119657  
4      -0.117877  
..           ...  
444    -0.302863  
445    -0.123316  
446     0.006540  
447    -0.357937  
448    -0.056604  

[449 rows x 770 columns]

### **Creating the Random Forest Classification Model on tfidf word embeddings**

In [109]:
# Define the features and target

X = tfidf_df.iloc[:, 2:]
y = tfidf_df['sentiment']

In [110]:
# Splitting the data into train and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state=16)

In [111]:
# Create an SVM model
import sklearn
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=500)
model_tfidf = rfc.fit(X_train, y_train)
model_tfidf

RandomForestClassifier(n_estimators=500)

In [112]:
y_pred_rfc_tfidf = rfc.predict(X_test)
y_pred_rfc_tfidf

array(['negative', 'neutral', 'negative', 'positive', 'negative',
       'negative', 'negative', 'negative', 'neutral', 'neutral',
       'neutral', 'positive', 'neutral', 'positive', 'neutral',
       'negative', 'positive', 'neutral', 'positive', 'neutral',
       'negative', 'neutral', 'positive', 'negative', 'negative',
       'negative', 'negative', 'neutral', 'neutral', 'negative',
       'neutral', 'negative', 'negative', 'neutral', 'negative',
       'negative', 'negative', 'negative', 'negative', 'positive',
       'positive', 'neutral', 'positive', 'negative', 'negative',
       'negative', 'neutral', 'neutral', 'negative', 'negative',
       'neutral', 'neutral', 'negative', 'positive', 'negative',
       'negative', 'neutral', 'positive', 'neutral', 'neutral', 'neutral',
       'negative', 'negative', 'neutral', 'negative', 'negative',
       'negative', 'positive', 'negative', 'negative', 'negative',
       'neutral', 'negative', 'positive', 'negative', 'neutral',
       '

In [113]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, precision_score, precision_recall_curve, auc, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred_rfc_tfidf)
conf_matrix = confusion_matrix(y_test, y_pred_rfc_tfidf)
precision = precision_score(y_test, y_pred_rfc_tfidf, average='weighted')
recall = recall_score(y_test, y_pred_rfc_tfidf, average='weighted')
f1 = f1_score(y_test, y_pred_rfc_tfidf, average='weighted')
class_report = classification_report(y_test, y_pred_rfc_tfidf, zero_division='warn')

# Print metrics
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Classification Report:")
print(class_report)

Accuracy: 0.74
Confusion Matrix:
[[28  5  1]
 [ 9 22  1]
 [ 4  3 17]]
Precision: 0.76
Recall: 0.74
F1-Score: 0.75
Classification Report:
              precision    recall  f1-score   support

    negative       0.68      0.82      0.75        34
     neutral       0.73      0.69      0.71        32
    positive       0.89      0.71      0.79        24

    accuracy                           0.74        90
   macro avg       0.77      0.74      0.75        90
weighted avg       0.76      0.74      0.75        90



### **Creating the Support Vector Machines Classification Model on tfidf word embeddings**

In [114]:
from sklearn.svm import SVC

# Instantiate the SVM model with a linear kernel
svm_model = SVC(kernel='linear')

# Fit the SVM model to the training data
svm_model_tfidf = svm_model.fit(X_train, y_train)

In [115]:
y_pred_svm_tfidf = svm_model_tfidf.predict(X_test)
y_pred_svm_tfidf

array(['negative', 'neutral', 'negative', 'positive', 'negative',
       'negative', 'negative', 'negative', 'neutral', 'neutral',
       'neutral', 'positive', 'negative', 'positive', 'negative',
       'negative', 'positive', 'positive', 'positive', 'negative',
       'negative', 'positive', 'positive', 'negative', 'negative',
       'negative', 'negative', 'negative', 'neutral', 'negative',
       'negative', 'negative', 'negative', 'neutral', 'negative',
       'negative', 'negative', 'negative', 'negative', 'positive',
       'positive', 'neutral', 'positive', 'negative', 'negative',
       'negative', 'neutral', 'neutral', 'negative', 'negative',
       'neutral', 'neutral', 'negative', 'positive', 'negative',
       'negative', 'neutral', 'positive', 'negative', 'neutral',
       'negative', 'negative', 'negative', 'neutral', 'negative',
       'negative', 'negative', 'positive', 'negative', 'positive',
       'negative', 'neutral', 'neutral', 'positive', 'negative',
       'neu

In [116]:
y_test

18     negative
30     positive
325    negative
281    positive
442    negative
         ...   
288     neutral
354     neutral
378    negative
343     neutral
427    positive
Name: sentiment, Length: 90, dtype: object

In [117]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, precision_score, precision_recall_curve, auc, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred_svm_tfidf)
conf_matrix = confusion_matrix(y_test, y_pred_svm_tfidf)
precision = precision_score(y_test, y_pred_svm_tfidf, average='weighted')
recall = recall_score(y_test, y_pred_svm_tfidf, average='weighted')
f1 = f1_score(y_test, y_pred_svm_tfidf, average='weighted')
class_report = classification_report(y_test, y_pred_svm_tfidf, zero_division='warn')

# Print metrics
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Classification Report:")
print(class_report)

Accuracy: 0.71
Confusion Matrix:
[[30  3  1]
 [14 16  2]
 [ 3  3 18]]
Precision: 0.73
Recall: 0.71
F1-Score: 0.70
Classification Report:
              precision    recall  f1-score   support

    negative       0.64      0.88      0.74        34
     neutral       0.73      0.50      0.59        32
    positive       0.86      0.75      0.80        24

    accuracy                           0.71        90
   macro avg       0.74      0.71      0.71        90
weighted avg       0.73      0.71      0.70        90



### **Creating the Random Forest Classification Model on Word2Vec word embeddings**

In [118]:
# Define feature matrix and Target vector

X = word2vec_df.iloc[:, 2:]
y = word2vec_df['sentiment']

In [119]:
# Split the dataset to train and test

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=16)

In [120]:
from sklearn.ensemble import RandomForestClassifier

rfc_model = RandomForestClassifier(n_estimators=500)
rfc_model_word2vec = rfc_model.fit(X_train, y_train)

In [121]:
y_pred_rfc_word2vec = rfc_model_word2vec.predict(X_test)
y_pred_rfc_word2vec

array(['negative', 'negative', 'negative', 'positive', 'negative',
       'negative', 'positive', 'negative', 'neutral', 'neutral',
       'neutral', 'positive', 'neutral', 'positive', 'neutral',
       'negative', 'positive', 'neutral', 'positive', 'negative',
       'neutral', 'positive', 'positive', 'negative', 'negative',
       'negative', 'negative', 'positive', 'neutral', 'neutral',
       'neutral', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'positive',
       'positive', 'negative', 'positive', 'positive', 'negative',
       'negative', 'neutral', 'positive', 'negative', 'negative',
       'negative', 'positive', 'negative', 'positive', 'negative',
       'negative', 'neutral', 'positive', 'neutral', 'neutral', 'neutral',
       'negative', 'positive', 'neutral', 'negative', 'negative',
       'negative', 'negative', 'negative', 'positive', 'negative',
       'neutral', 'neutral', 'positive', 'negative', 'neutral',
  

In [122]:
y_test

18     negative
30     positive
325    negative
281    positive
442    negative
         ...   
288     neutral
354     neutral
378    negative
343     neutral
427    positive
Name: sentiment, Length: 90, dtype: object

In [123]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, precision_score, precision_recall_curve, auc, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred_rfc_word2vec)
conf_matrix = confusion_matrix(y_test, y_pred_rfc_word2vec)
precision = precision_score(y_test, y_pred_rfc_word2vec, average='weighted')
recall = recall_score(y_test, y_pred_rfc_word2vec, average='weighted')
f1 = f1_score(y_test, y_pred_rfc_word2vec, average='weighted')
class_report = classification_report(y_test, y_pred_rfc_word2vec, zero_division='warn')

# Print metrics
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Classification Report:")
print(class_report)

Accuracy: 0.69
Confusion Matrix:
[[26  4  4]
 [ 8 19  5]
 [ 7  0 17]]
Precision: 0.71
Recall: 0.69
F1-Score: 0.69
Classification Report:
              precision    recall  f1-score   support

    negative       0.63      0.76      0.69        34
     neutral       0.83      0.59      0.69        32
    positive       0.65      0.71      0.68        24

    accuracy                           0.69        90
   macro avg       0.70      0.69      0.69        90
weighted avg       0.71      0.69      0.69        90



### **Creating the Support Vector Machines Classification Model on Word2Vec word embeddings**

In [124]:
X = word2vec_df.iloc[:, 2:]
y = word2vec_df['sentiment']

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 16)

In [126]:
from sklearn.svm import SVC

# Instantiate the SVM model with a linear kernel
svm_model = SVC(kernel='linear')

# Fit the SVM model to the training data
svm_model_word2vec = svm_model.fit(X_train, y_train)

In [127]:
y_train.value_counts()

sentiment
negative    140
neutral     115
positive    104
Name: count, dtype: int64

In [128]:
y_pred_svm_word2vec = svm_model_word2vec.predict(X_test)
y_pred_svm_word2vec

array(['negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negative',
       'negative', 'negative', 'negative', 'negative', 'negati

In [129]:
y_test

18     negative
30     positive
325    negative
281    positive
442    negative
         ...   
288     neutral
354     neutral
378    negative
343     neutral
427    positive
Name: sentiment, Length: 90, dtype: object

In [130]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, precision_score, precision_recall_curve, auc, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred_svm_word2vec)
conf_matrix = confusion_matrix(y_test, y_pred_svm_word2vec)
precision = precision_score(y_test, y_pred_svm_word2vec, average='weighted')
recall = recall_score(y_test, y_pred_svm_word2vec, average='weighted')
f1 = f1_score(y_test, y_pred_svm_word2vec, average='weighted')
class_report = classification_report(y_test, y_pred_svm_word2vec)

# Print metrics
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Classification Report:")
print(class_report)

Accuracy: 0.38
Confusion Matrix:
[[34  0  0]
 [32  0  0]
 [24  0  0]]
Precision: 0.14
Recall: 0.38
F1-Score: 0.21
Classification Report:
              precision    recall  f1-score   support

    negative       0.38      1.00      0.55        34
     neutral       0.00      0.00      0.00        32
    positive       0.00      0.00      0.00        24

    accuracy                           0.38        90
   macro avg       0.13      0.33      0.18        90
weighted avg       0.14      0.38      0.21        90



c:\Users\dwara\OneDrive\Desktop\Ryan\CSCN8010\venv\CSCN8010_classic_ml\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dwara\OneDrive\Desktop\Ryan\CSCN8010\venv\CSCN8010_classic_ml\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\dwara\OneDrive\Desktop\Ryan\CSCN8010\venv\CSCN8010_classic_ml\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control 

### **Creating the Random Forest Classification Model on BERT word embeddings**

In [131]:
X = embedding_df.iloc[:,2:]
y = embedding_df['sentiment']

In [132]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 16)

In [133]:
from sklearn.ensemble import RandomForestClassifier

rfc_model = RandomForestClassifier(n_estimators=500)
rfc_model_BERT = rfc_model.fit(X_train, y_train)

In [134]:
y_pred_rfc_BERT = rfc_model_BERT.predict(X_test)
y_pred_rfc_BERT

array(['negative', 'positive', 'negative', 'positive', 'negative',
       'positive', 'negative', 'negative', 'negative', 'neutral',
       'neutral', 'positive', 'negative', 'positive', 'neutral',
       'negative', 'positive', 'neutral', 'positive', 'negative',
       'negative', 'negative', 'positive', 'negative', 'negative',
       'positive', 'negative', 'neutral', 'neutral', 'negative',
       'negative', 'negative', 'negative', 'neutral', 'negative',
       'negative', 'negative', 'negative', 'negative', 'positive',
       'positive', 'neutral', 'positive', 'negative', 'negative',
       'negative', 'neutral', 'neutral', 'negative', 'negative',
       'negative', 'negative', 'negative', 'positive', 'negative',
       'negative', 'neutral', 'positive', 'neutral', 'neutral', 'neutral',
       'negative', 'neutral', 'neutral', 'negative', 'negative',
       'negative', 'negative', 'negative', 'positive', 'positive',
       'neutral', 'negative', 'positive', 'negative', 'neutral',
 

In [135]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, precision_score, precision_recall_curve, auc, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred_rfc_BERT)
conf_matrix = confusion_matrix(y_test, y_pred_rfc_BERT)
precision = precision_score(y_test, y_pred_rfc_BERT, average='weighted')
recall = recall_score(y_test, y_pred_rfc_BERT, average='weighted')
f1 = f1_score(y_test, y_pred_rfc_BERT, average='weighted')
class_report = classification_report(y_test, y_pred_rfc_BERT, zero_division='warn')

# Print metrics
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Classification Report:")
print(class_report)

Accuracy: 0.82
Confusion Matrix:
[[34  0  0]
 [11 19  2]
 [ 1  2 21]]
Precision: 0.84
Recall: 0.82
F1-Score: 0.81
Classification Report:
              precision    recall  f1-score   support

    negative       0.74      1.00      0.85        34
     neutral       0.90      0.59      0.72        32
    positive       0.91      0.88      0.89        24

    accuracy                           0.82        90
   macro avg       0.85      0.82      0.82        90
weighted avg       0.84      0.82      0.81        90



### **Creating the SVM Classification Model on BERT word embeddings**

In [136]:
from sklearn.svm import SVC

# Instantiate the SVM model with a linear kernel
svm_model = SVC(kernel='linear')

# Fit the SVM model to the training data
svm_model_BERT = svm_model.fit(X_train, y_train)

In [137]:
y_pred_svm_BERT = svm_model_BERT.predict(X_test)
y_pred_svm_BERT

array(['negative', 'positive', 'negative', 'positive', 'negative',
       'positive', 'negative', 'negative', 'negative', 'neutral',
       'neutral', 'positive', 'neutral', 'positive', 'neutral',
       'negative', 'positive', 'positive', 'positive', 'negative',
       'negative', 'neutral', 'positive', 'negative', 'negative',
       'neutral', 'negative', 'neutral', 'neutral', 'negative', 'neutral',
       'negative', 'negative', 'neutral', 'negative', 'negative',
       'negative', 'neutral', 'neutral', 'positive', 'positive',
       'positive', 'positive', 'negative', 'negative', 'negative',
       'neutral', 'neutral', 'negative', 'negative', 'negative',
       'negative', 'negative', 'positive', 'negative', 'negative',
       'neutral', 'positive', 'neutral', 'neutral', 'negative',
       'negative', 'negative', 'neutral', 'negative', 'negative',
       'negative', 'neutral', 'negative', 'positive', 'positive',
       'neutral', 'neutral', 'positive', 'negative', 'neutral', 'neut

In [138]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, precision_score, precision_recall_curve, auc, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred_svm_BERT)
conf_matrix = confusion_matrix(y_test, y_pred_svm_BERT)
precision = precision_score(y_test, y_pred_svm_BERT, average='weighted')
recall = recall_score(y_test, y_pred_svm_BERT, average='weighted')
f1 = f1_score(y_test, y_pred_svm_BERT, average='weighted')
class_report = classification_report(y_test, y_pred_svm_BERT, zero_division='warn')

# Print metrics
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print("Classification Report:")
print(class_report)

Accuracy: 0.79
Confusion Matrix:
[[30  4  0]
 [ 9 21  2]
 [ 1  3 20]]
Precision: 0.79
Recall: 0.79
F1-Score: 0.79
Classification Report:
              precision    recall  f1-score   support

    negative       0.75      0.88      0.81        34
     neutral       0.75      0.66      0.70        32
    positive       0.91      0.83      0.87        24

    accuracy                           0.79        90
   macro avg       0.80      0.79      0.79        90
weighted avg       0.79      0.79      0.79        90

